package org.programadoresjava.bibliotecadigital.controllers1;
// Generated 20-ago-2012 22:36:35 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Bitacora generated by hbm2java
 */
public class Bitacora  implements java.io.Serializable {


     private BitacoraId id;
     private Usuarios usuarios;
     private Date fechaEntrada;
     private Date fechaSalida;

    public Bitacora() {
    }

	
    public Bitacora(BitacoraId id, Usuarios usuarios) {
        this.id = id;
        this.usuarios = usuarios;
    }
    public Bitacora(BitacoraId id, Usuarios usuarios, Date fechaEntrada, Date fechaSalida) {
       this.id = id;
       this.usuarios = usuarios;
       this.fechaEntrada = fechaEntrada;
       this.fechaSalida = fechaSalida;
    }
   
    public BitacoraId getId() {
        return this.id;
    }
    
    public void setId(BitacoraId id) {
        this.id = id;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Date getFechaEntrada() {
        return this.fechaEntrada;
    }
    
    public void setFechaEntrada(Date fechaEntrada) {
        this.fechaEntrada = fechaEntrada;
    }
    public Date getFechaSalida() {
        return this.fechaSalida;
    }
    
    public void setFechaSalida(Date fechaSalida) {
        this.fechaSalida = fechaSalida;
    }




}


