package org.programadoresjava.bibliotecadigital.controllers1;
// Generated 20-ago-2012 22:36:35 by Hibernate Tools 3.2.1.GA



/**
 * BitacoraId generated by hbm2java
 */
public class BitacoraId  implements java.io.Serializable {


     private int idBitacora;
     private String usuariosNoIfe;

    public BitacoraId() {
    }

    public BitacoraId(int idBitacora, String usuariosNoIfe) {
       this.idBitacora = idBitacora;
       this.usuariosNoIfe = usuariosNoIfe;
    }
   
    public int getIdBitacora() {
        return this.idBitacora;
    }
    
    public void setIdBitacora(int idBitacora) {
        this.idBitacora = idBitacora;
    }
    public String getUsuariosNoIfe() {
        return this.usuariosNoIfe;
    }
    
    public void setUsuariosNoIfe(String usuariosNoIfe) {
        this.usuariosNoIfe = usuariosNoIfe;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BitacoraId) ) return false;
		 BitacoraId castOther = ( BitacoraId ) other; 
         
		 return (this.getIdBitacora()==castOther.getIdBitacora())
 && ( (this.getUsuariosNoIfe()==castOther.getUsuariosNoIfe()) || ( this.getUsuariosNoIfe()!=null && castOther.getUsuariosNoIfe()!=null && this.getUsuariosNoIfe().equals(castOther.getUsuariosNoIfe()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdBitacora();
         result = 37 * result + ( getUsuariosNoIfe() == null ? 0 : this.getUsuariosNoIfe().hashCode() );
         return result;
   }   


}


