package org.programadoresjava.bibliotecadigital.controllers1;
// Generated 20-ago-2012 22:36:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Equipos generated by hbm2java
 */
public class Equipos  implements java.io.Serializable {


     private String noSerie;
     private String marca;
     private String modelo;
     private boolean seleccionado;
     private String descripcion;
     private Set usuarioses = new HashSet(0);

    public Equipos() {
    }

	
    public Equipos(String noSerie, String marca, String modelo, boolean seleccionado) {
        this.noSerie = noSerie;
        this.marca = marca;
        this.modelo = modelo;
        this.seleccionado = seleccionado;
    }
    public Equipos(String noSerie, String marca, String modelo, boolean seleccionado, String descripcion, Set usuarioses) {
       this.noSerie = noSerie;
       this.marca = marca;
       this.modelo = modelo;
       this.seleccionado = seleccionado;
       this.descripcion = descripcion;
       this.usuarioses = usuarioses;
    }
   
    public String getNoSerie() {
        return this.noSerie;
    }
    
    public void setNoSerie(String noSerie) {
        this.noSerie = noSerie;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public boolean isSeleccionado() {
        return this.seleccionado;
    }
    
    public void setSeleccionado(boolean seleccionado) {
        this.seleccionado = seleccionado;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }




}


