package org.programadoresjava.bibliotecadigital.controllers1;
// Generated 20-ago-2012 22:36:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private String noIfe;
     private String nombre;
     private String apaterno;
     private String amaterno;
     private String compania;
     private String email;
     private String contrasenia;
     private boolean estatus;
     private Set equiposes = new HashSet(0);
     private Set bitacoras = new HashSet(0);

    public Usuarios() {
    }

	
    public Usuarios(String noIfe, String nombre, String apaterno, String amaterno, String compania, String email, String contrasenia, boolean estatus) {
        this.noIfe = noIfe;
        this.nombre = nombre;
        this.apaterno = apaterno;
        this.amaterno = amaterno;
        this.compania = compania;
        this.email = email;
        this.contrasenia = contrasenia;
        this.estatus = estatus;
    }
    public Usuarios(String noIfe, String nombre, String apaterno, String amaterno, String compania, String email, String contrasenia, boolean estatus, Set equiposes, Set bitacoras) {
       this.noIfe = noIfe;
       this.nombre = nombre;
       this.apaterno = apaterno;
       this.amaterno = amaterno;
       this.compania = compania;
       this.email = email;
       this.contrasenia = contrasenia;
       this.estatus = estatus;
       this.equiposes = equiposes;
       this.bitacoras = bitacoras;
    }
   
    public String getNoIfe() {
        return this.noIfe;
    }
    
    public void setNoIfe(String noIfe) {
        this.noIfe = noIfe;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApaterno() {
        return this.apaterno;
    }
    
    public void setApaterno(String apaterno) {
        this.apaterno = apaterno;
    }
    public String getAmaterno() {
        return this.amaterno;
    }
    
    public void setAmaterno(String amaterno) {
        this.amaterno = amaterno;
    }
    public String getCompania() {
        return this.compania;
    }
    
    public void setCompania(String compania) {
        this.compania = compania;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public boolean isEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(boolean estatus) {
        this.estatus = estatus;
    }
    public Set getEquiposes() {
        return this.equiposes;
    }
    
    public void setEquiposes(Set equiposes) {
        this.equiposes = equiposes;
    }
    public Set getBitacoras() {
        return this.bitacoras;
    }
    
    public void setBitacoras(Set bitacoras) {
        this.bitacoras = bitacoras;
    }




}


