package org.programadoresjava.bibliotecadigital.models;
// Generated 20-ago-2012 22:58:13 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bitacora generated by hbm2java
 */
@Entity
@Table(name="bitacora"
    ,catalog="mydb"
)
public class Bitacora  implements java.io.Serializable {


     private BitacoraId id;
     private Usuarios usuarios;
     private Date fechaEntrada;
     private Date fechaSalida;

    public Bitacora() {
    }

	
    public Bitacora(BitacoraId id, Usuarios usuarios) {
        this.id = id;
        this.usuarios = usuarios;
    }
    public Bitacora(BitacoraId id, Usuarios usuarios, Date fechaEntrada, Date fechaSalida) {
       this.id = id;
       this.usuarios = usuarios;
       this.fechaEntrada = fechaEntrada;
       this.fechaSalida = fechaSalida;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idBitacora", column=@Column(name="idBitacora", nullable=false) ), 
        @AttributeOverride(name="usuariosNoIfe", column=@Column(name="Usuarios_No_IFE", nullable=false, length=20) ) } )
    public BitacoraId getId() {
        return this.id;
    }
    
    public void setId(BitacoraId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Usuarios_No_IFE", nullable=false, insertable=false, updatable=false)
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Fecha_Entrada", length=19)
    public Date getFechaEntrada() {
        return this.fechaEntrada;
    }
    
    public void setFechaEntrada(Date fechaEntrada) {
        this.fechaEntrada = fechaEntrada;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Fecha_Salida", length=19)
    public Date getFechaSalida() {
        return this.fechaSalida;
    }
    
    public void setFechaSalida(Date fechaSalida) {
        this.fechaSalida = fechaSalida;
    }




}


