package org.programadoresjava.bibliotecadigital.models;
// Generated 20-ago-2012 22:58:13 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name="usuarios"
    ,catalog="mydb"
)
public class Usuarios  implements java.io.Serializable {


     private String noIfe;
     private String nombre;
     private String apaterno;
     private String amaterno;
     private String compania;
     private String email;
     private String contrasenia;
     private boolean estatus;
     private Set equiposes = new HashSet(0);
     private Set bitacoras = new HashSet(0);

    public Usuarios() {
    }

	
    public Usuarios(String noIfe, String nombre, String apaterno, String amaterno, String compania, String email, String contrasenia, boolean estatus) {
        this.noIfe = noIfe;
        this.nombre = nombre;
        this.apaterno = apaterno;
        this.amaterno = amaterno;
        this.compania = compania;
        this.email = email;
        this.contrasenia = contrasenia;
        this.estatus = estatus;
    }
    public Usuarios(String noIfe, String nombre, String apaterno, String amaterno, String compania, String email, String contrasenia, boolean estatus, Set equiposes, Set bitacoras) {
       this.noIfe = noIfe;
       this.nombre = nombre;
       this.apaterno = apaterno;
       this.amaterno = amaterno;
       this.compania = compania;
       this.email = email;
       this.contrasenia = contrasenia;
       this.estatus = estatus;
       this.equiposes = equiposes;
       this.bitacoras = bitacoras;
    }
   
     @Id 
    
    @Column(name="No_IFE", unique=true, nullable=false, length=20)
    public String getNoIfe() {
        return this.noIfe;
    }
    
    public void setNoIfe(String noIfe) {
        this.noIfe = noIfe;
    }
    
    @Column(name="Nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="Apaterno", nullable=false, length=45)
    public String getApaterno() {
        return this.apaterno;
    }
    
    public void setApaterno(String apaterno) {
        this.apaterno = apaterno;
    }
    
    @Column(name="Amaterno", nullable=false, length=45)
    public String getAmaterno() {
        return this.amaterno;
    }
    
    public void setAmaterno(String amaterno) {
        this.amaterno = amaterno;
    }
    
    @Column(name="Compania", nullable=false, length=45)
    public String getCompania() {
        return this.compania;
    }
    
    public void setCompania(String compania) {
        this.compania = compania;
    }
    
    @Column(name="Email", nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="Contrasenia", nullable=false, length=45)
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    
    @Column(name="Estatus", nullable=false)
    public boolean isEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(boolean estatus) {
        this.estatus = estatus;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="equipos_has_usuarios", catalog="mydb", joinColumns = { 
        @JoinColumn(name="Usuarios_No_IFE", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="Equipos_No_serie", nullable=false, updatable=false) })
    public Set getEquiposes() {
        return this.equiposes;
    }
    
    public void setEquiposes(Set equiposes) {
        this.equiposes = equiposes;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usuarios")
    public Set getBitacoras() {
        return this.bitacoras;
    }
    
    public void setBitacoras(Set bitacoras) {
        this.bitacoras = bitacoras;
    }




}


